function net = Fierro_Reyes_Arquitectura()

f=1/100 ;
net.layers = {} ;
%Size Input: 128x128x1
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(15,15,1,25, 'single'), ...
                           'biases', zeros(1, 25, 'single'), ...
                           'stride', 2, ...
                           'pad', 0) ;
                       
%Size Input: 57x57x25
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [4 4], ...
                           'stride', 3, ...
                           'pad', 0);
%Size Input: 18x18x25
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(7,7,25,25, 'single'), ...
                           'biases', zeros(1, 25, 'single'), ...
                           'stride', 3, ...
                           'pad', 0) ;
%Size Input: 4x4x25
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [4 4], ...
                           'stride', 1, ...
                           'pad', 0) ;
                       
%Size Input: 1x1x25                       
net.layers{end+1} = struct('type', 'relu') ;
net.layers{end+1} = struct('type', 'softmaxloss') ;


