function net = initializeTextonsCNN()

f=1/100 ;
net.layers = {} ;
% Input image size = [128 128 1]
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(9, 9, 1, 16, 'single'), ...
                           'biases', zeros(1, 16, 'single'), ...
                           'stride', 3, ...
                           'pad', 0);
% layer 1 output size = [40 40 16]
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [4 4], ...
                           'stride', 4, ...
                           'pad', 0) ;
% layer 2 output size = [10 10 16]
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(5, 5, 16, 100, 'single'), ...
                           'biases', zeros(1, 100,'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
% layer 3 output size = [6 6 100]
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(5, 5, 100, 25, 'single'), ...
                           'biases', zeros(1, 25, 'single'), ...
                           'stride', 1, ...
                           'pad', 0);
% layer 4 output size = [2 2 25]
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;
% layer 5 output size = [1 1 25]
net.layers{end+1} = struct('type', 'softmaxloss') ;
% layer 6 output size = [1 1 25]
